/**
 * @file clean.ts
 * @description Removes all generated artifacts, caches, and build outputs
 * from the contracts package. Run after major Solidity refactors or when
 * the compilation cache becomes stale.
 *
 * Called by: pnpm clean  (after hardhat clean)
 *
 * Directories removed:
 *   - artifacts/        Compiled ABIs and bytecode
 *   - cache/            Solidity compilation cache
 *   - typechain-types/  Generated TypeScript bindings
 *   - coverage/         Istanbul coverage reports
 *   - gas-report.txt    Gas reporter output
 *   - dist/             TypeScript compiled output
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.join(__dirname, '..');

const TARGETS: Array<{ path: string; type: 'dir' | 'file' }> = [
  { path: 'artifacts', type: 'dir' },
  { path: 'cache', type: 'dir' },
  { path: 'typechain-types', type: 'dir' },
  { path: 'coverage', type: 'dir' },
  { path: 'dist', type: 'dir' },
  { path: 'gas-report.txt', type: 'file' },
  { path: '.solcover.js', type: 'file' }, // generated by coverage plugin
];

function removeTarget(target: { path: string; type: 'dir' | 'file' }): void {
  const fullPath = path.join(ROOT, target.path);

  if (!fs.existsSync(fullPath)) {
    console.log(`  ⏭  ${target.path} — not found, skipping`);
    return;
  }

  if (target.type === 'dir') {
    fs.rmSync(fullPath, { recursive: true, force: true });
  } else {
    fs.unlinkSync(fullPath);
  }

  console.log(`  🗑  ${target.path} removed`);
}

function main(): void {
  console.log('\n🧹 Cleaning contracts package...\n');

  for (const target of TARGETS) {
    removeTarget(target);
  }

  console.log('\n✅ Clean complete\n');
}

main();
