#!/usr/bin/env sh
# Husky commit-msg hook
# Validates commit message format against Conventional Commits spec.
# Configuration: "commitlint" key in root package.json.
# Docs: https://commitlint.js.org

. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "$1"
